server:
  jetty:
    max-http-post-size: 0
  port: 9880
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://172.168.2.16:3307/auth?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root@Freitx.com
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jackson:
    default-property-inclusion: non_null

memcached:
  host: 172.168.2.16
  port: 11211

core:
  debug: true  #调试开关
  sendgrid:   #发邮件配置
    api: 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  #邮件接口api配置
    sendby: admin@autossav.com
    templates:                                                      #模板配置
      RESET_PASSWORD: d-fe20d9bdb7cb4d808260a3354072da23            #重置密码或者用户名
  sms:  #短信配置
    apiKey: 3223caf1
    apiSecret: c784417c2c86e0d9
    from: 12067177275
